// AQMS per-document administration: QA/Admin can edit each process/procedure in place.
(function(){
 const LOGIN_KEY='wave_mes_demo_login_v2';
 const KEY='wave_mes_aqms_docs_v2', HIST='wave_mes_aqms_history_v1', CTRL='wave_mes_aqms_controlled_files_v1';
 const session=()=>{try{return JSON.parse(sessionStorage.getItem(LOGIN_KEY)||'null')}catch(e){return null}};
 const canEdit=()=>['관리자','품질'].includes(String(session()?.role||''));
 const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch(e){return d}};
 const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 function log(action,before,after,reason){const h=load(HIST,[]);h.unshift({at:new Date().toLocaleString('ko-KR'),no:after?.no||before?.no,title:after?.title||before?.title,from:before?.rev||'-',to:after?.rev||'-',user:session()?.name||'미로그인',reason:`${action}: ${reason}`});save(HIST,h);try{window.waveMesAudit?.('AQMS '+action,after?.no||before?.no,after?.no||before?.no,before,after,reason)}catch(e){}}
 function refresh(){try{window.waveAqmsV2?.show()}catch(e){location.reload()}}
 function retire(id){if(!canEdit())return;const db=load(KEY,[]),d=db.find(x=>x.id===id);if(!d)return;const reason=prompt(`폐기/비활성 사유를 입력하세요.\n${d.no} / ${d.title}`,'');if(!reason?.trim())return; if(!confirm('이 문서를 현재 AQMS 목록에서 비활성 처리할까요?\n기존 이력은 보존됩니다.'))return;const before=JSON.parse(JSON.stringify(d));d.inactive=true;d.inactiveAt=new Date().toISOString();d.inactiveBy=session()?.name||'';d.inactiveReason=reason.trim();save(KEY,db);log('폐기/비활성',before,d,reason.trim());refresh()}
 function modal(id){if(!canEdit())return;const db=load(KEY,[]),d=db.find(x=>x.id===id);if(!d)return;document.getElementById('aqmsRowEditModal')?.remove();const m=document.createElement('div');m.id='aqmsRowEditModal';m.style='position:fixed;inset:0;background:#0008;z-index:100000;display:flex;align-items:center;justify-content:center;padding:20px';m.innerHTML=`<div style="width:min(760px,96vw);max-height:92vh;overflow:auto;background:#fff;border-radius:16px;padding:20px;box-shadow:0 25px 70px #0005"><div style="display:flex;align-items:center;gap:10px;margin-bottom:15px"><div><b style="font-size:20px">AQMS 문서 수정</b><div style="font-size:11px;color:#667">품질 / 관리자 전용 · 모든 변경은 이력에 기록됩니다.</div></div><button id="arClose" style="margin-left:auto">닫기</button></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><label>구분<select id="arType" style="width:100%;padding:9px"><option>프로세스</option><option>지침서</option></select></label><label>문서번호<input id="arNo" style="width:100%;box-sizing:border-box;padding:9px"></label><label style="grid-column:1/-1">문서명<input id="arTitle" style="width:100%;box-sizing:border-box;padding:9px"></label><label>Rev<input id="arRev" style="width:100%;box-sizing:border-box;padding:9px"></label><label>주관부서<input id="arOwner" style="width:100%;box-sizing:border-box;padding:9px"></label><label>제정일<input id="arEnact" style="width:100%;box-sizing:border-box;padding:9px"></label><label>최근 개정일<input id="arUpdate" style="width:100%;box-sizing:border-box;padding:9px"></label><label style="grid-column:1/-1">양식 / 산출물 <span style="font-size:10px;color:#778">(줄바꿈으로 구분)</span><textarea id="arOutputs" rows="7" style="width:100%;box-sizing:border-box;padding:9px"></textarea></label><label style="grid-column:1/-1">원본 위치 하이퍼링크<input id="arLink" style="width:100%;box-sizing:border-box;padding:9px"></label><label style="grid-column:1/-1">변경 사유 <b style="color:#c33">필수</b><textarea id="arReason" rows="3" style="width:100%;box-sizing:border-box;padding:9px"></textarea></label><label style="grid-column:1/-1;padding:12px;background:#f5fafc;border-radius:10px">승인 PDF 교체/등록 <input id="arPdf" type="file" accept="application/pdf" style="display:block;margin-top:8px"></label></div><div style="display:flex;gap:8px;margin-top:14px"><button id="arSave" style="padding:10px 15px;border:0;border-radius:9px;background:#087db8;color:white;font-weight:800">변경 저장</button><button id="arRetire" style="margin-left:auto;padding:10px 15px;border:1px solid #d55;border-radius:9px;background:#fff;color:#c33;font-weight:800">문서 폐기 / 비활성</button></div></div>`;document.body.appendChild(m);
 const q=x=>m.querySelector(x);q('#arType').value=d.type;q('#arNo').value=d.no;q('#arTitle').value=d.title;q('#arRev').value=d.rev;q('#arOwner').value=d.owner;q('#arEnact').value=d.enact||'';q('#arUpdate').value=d.update||'';q('#arOutputs').value=(d.outputs||[]).join('\n');q('#arLink').value=d.link||'';q('#arClose').onclick=()=>m.remove();q('#arRetire').onclick=()=>{m.remove();retire(id)};
 q('#arSave').onclick=()=>{const reason=q('#arReason').value.trim();if(!reason)return alert('변경 사유를 입력해야 합니다.');const before=JSON.parse(JSON.stringify(d));d.type=q('#arType').value;d.no=q('#arNo').value.trim();d.title=q('#arTitle').value.trim();d.rev=q('#arRev').value.trim();d.owner=q('#arOwner').value.trim();d.enact=q('#arEnact').value.trim();d.update=q('#arUpdate').value.trim();d.date=d.update&&d.update!=='-'?d.update:d.enact;d.outputs=q('#arOutputs').value.split(/\n+/).map(x=>x.trim()).filter(Boolean);d.link=q('#arLink').value.trim();const file=q('#arPdf').files[0];const finish=()=>{save(KEY,db);log('문서 수정',before,d,reason);m.remove();refresh()};if(file){const rd=new FileReader();rd.onload=()=>{const c=load(CTRL,{}),old=c[d.no];c[d.no]={no:d.no,rev:d.rev,title:d.title,fileName:file.name,data:rd.result,link:d.link,reason,user:session()?.name||'',date:new Date().toLocaleString('ko-KR'),previous:old?{rev:old.rev,fileName:old.fileName,date:old.date}:null};save(CTRL,c);finish()};rd.readAsDataURL(file)}else finish();};}
 function decorate(){const root=document.getElementById('aqmsView');if(!root)return;document.getElementById('aqmsQualityEditBtn')?.remove();const top=document.getElementById('aqmsUploadBtn');if(top)top.style.display='none';root.querySelectorAll('.head .btn.secondary').forEach(b=>{if(/Rev|문서정보|수정/.test(b.textContent||''))b.style.display='none'});const db=load(KEY,[]);root.querySelectorAll('.aq-row[data-aqid]').forEach(r=>{const d=db.find(x=>x.id===r.dataset.aqid);if(d?.inactive){r.style.display='none';return}let tools=r.querySelector('.aq-row-tools');if(!canEdit()){tools?.remove();return}if(!tools){tools=document.createElement('div');tools.className='aq-row-tools';tools.style='position:absolute;right:9px;top:50%;transform:translateY(-50%);display:flex;gap:5px';r.style.position='relative';r.style.paddingRight='92px';tools.innerHTML='<button data-act="edit" style="padding:5px 8px;border:1px solid #9dcddd;border-radius:7px;background:#fff;color:#0877a5;font-size:10px;font-weight:800;cursor:pointer">수정</button><button data-act="retire" style="padding:5px 8px;border:1px solid #efb3b3;border-radius:7px;background:#fff;color:#c33;font-size:10px;font-weight:800;cursor:pointer">폐기</button>';r.appendChild(tools);tools.onclick=e=>{e.preventDefault();e.stopPropagation();const a=e.target.closest('button')?.dataset.act;if(a==='edit')modal(r.dataset.aqid);if(a==='retire')retire(r.dataset.aqid)}}});}
 setTimeout(decorate,250);setTimeout(decorate,900);setInterval(decorate,1200);
 document.addEventListener('click',e=>{if(e.target.closest('#aqmsView'))setTimeout(decorate,30)});
})();