// WAVEPIA AQMS Document Center - additive layer, isolated from MES runtime
(function(){
 const KEY='wave_mes_aqms_docs_v1', HIST='wave_mes_aqms_history_v1';
 const seed=[
  {id:'P-PROD',type:'프로세스',no:'문서번호 미등록',title:'생산 및 서비스 제공',rev:'미등록',date:'-',owner:'생산',link:'',status:'현행',outputs:['작업요청서','디지털 LTC','작업실적','포장 기록'],related:['I-TRACE','I-INSP','I-NC']},
  {id:'P-PUR',type:'프로세스',no:'문서번호 미등록',title:'구매 및 외부공급자 관리',rev:'미등록',date:'-',owner:'구매 / 자재',link:'',status:'현행',outputs:['발주 기록','입고 기록','수입검사 기록','공급자 평가'],related:['I-INSP']},
  {id:'P-DEV',type:'프로세스',no:'문서번호 미등록',title:'설계 및 개발 관리',rev:'미등록',date:'-',owner:'개발',link:'',status:'현행',outputs:['개발계획','설계검토 기록','검증 / 유효성 확인 기록','변경 기록'],related:['I-CONFIG']},
  {id:'P-NC',type:'프로세스',no:'문서번호 미등록',title:'부적합 및 시정조치 관리',rev:'미등록',date:'-',owner:'품질',link:'',status:'현행',outputs:['NCR','CAR','8D Report','시정 / 예방조치 기록'],related:['I-NC']},
  {id:'I-TRACE',type:'지침서',no:'문서번호 미등록',title:'식별 및 추적성 관리',rev:'미등록',date:'-',owner:'생산 / 품질',link:'',status:'현행',outputs:['LOT / LTC 식별 기록','PO / 기안번호 추적 기록','공정 이력'],related:['P-PROD']},
  {id:'I-INSP',type:'지침서',no:'문서번호 미등록',title:'검사 업무',rev:'미등록',date:'-',owner:'품질',link:'',status:'현행',outputs:['수입검사 기록','공정검사 기록','출하검사 기록','검사 성적서'],related:['P-PROD','P-PUR']},
  {id:'I-NC',type:'지침서',no:'문서번호 미등록',title:'부적합 관리',rev:'미등록',date:'-',owner:'품질',link:'',status:'현행',outputs:['부적합 보고서','HOLD / CLEAR 이력','처리 판정 기록'],related:['P-NC','P-PROD']},
  {id:'I-CONFIG',type:'지침서',no:'문서번호 미등록',title:'형상 및 변경 관리',rev:'미등록',date:'-',owner:'개발 / 품질',link:'',status:'현행',outputs:['BOM Rev','도면 Rev','변경 승인 기록','형상 기준선'],related:['P-DEV']}
 ];
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const load=(k,d)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??d}catch(e){return d}};
 const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 let docs=load(KEY,null); if(!Array.isArray(docs)||!docs.length){docs=seed;save(KEY,docs)}
 docs.forEach(d=>{if(!('status' in d))d.status='현행';if(!Array.isArray(d.outputs))d.outputs=[];if(!Array.isArray(d.related))d.related=[]});
 let selected=docs[0]?.id||'', currentTab='대시보드';
 const history=()=>load(HIST,[]);
 const actor=()=>{try{return JSON.parse(sessionStorage.getItem('wave_mes_demo_login_v2')||'null')?.name||'DEMO 사용자'}catch(e){return 'DEMO 사용자'}};
 function audit(action,d,before,after,reason){const h=history();h.unshift({at:new Date().toLocaleString('ko-KR'),action,id:d.id,no:d.no,title:d.title,from:before?.rev||'-',to:after?.rev||d.rev,reason:reason||'-',user:actor()});save(HIST,h);try{window.waveMesAudit?.('AQMS '+action,d.no,d.no,before,after,reason)}catch(e){}}
 function style(){if(document.getElementById('aqmsDocStyle2'))return;const x=document.createElement('style');x.id='aqmsDocStyle2';x.textContent=`
 #aqmsView{min-height:calc(100vh - 120px)}#aqmsView .aqhero{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;padding:18px 20px;background:linear-gradient(135deg,#0878bd,#0a557f);color:white;border-radius:14px;margin-bottom:14px;box-shadow:0 8px 24px #0a557f1f}#aqmsView .aqhero h2{font-size:21px;margin:0 0 5px}#aqmsView .aqhero p{margin:0;color:#d9f3ff;font-size:10px;line-height:1.6}.aqhero-badge{background:#ffffff20;border:1px solid #ffffff42;border-radius:999px;padding:7px 11px;font-size:9px;font-weight:900;white-space:nowrap}
 #aqmsView .aqtabs{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:14px;background:#fff;padding:8px;border:1px solid #d9e6ed;border-radius:11px}#aqmsView .aqtabs button{border:0;background:transparent;border-radius:8px;padding:9px 13px;font-size:10px;font-weight:800;color:#58707d;cursor:pointer}#aqmsView .aqtabs button.on{background:#0b78b5;color:#fff}.aqmetrics{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:14px}.aqmetric{background:#fff;border:1px solid #d9e6ed;border-radius:11px;padding:13px}.aqmetric span{font-size:9px;color:#71838d}.aqmetric b{display:block;font-size:23px;margin-top:5px;color:#17394b}.aqmetric.good b{color:#16855f}.aqmetric.warn b{color:#bd7a08}
 .aqdashgrid{display:grid;grid-template-columns:1.4fr .9fr;gap:12px}.aqsection{background:#fff;border:1px solid #d9e6ed;border-radius:12px;padding:15px;margin-bottom:12px}.aqsection-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.aqsection-title b{font-size:13px}.aqflow{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.aqflow .node{border:1px solid #dce8ee;border-radius:10px;padding:11px;background:#f8fbfd;cursor:pointer;min-height:78px}.aqflow .node:hover{border-color:#2aa3d5;background:#eef9fd}.aqflow .node .kind{font-size:8px;color:#1381ad;font-weight:900}.aqflow .node b{display:block;font-size:11px;margin-top:5px}.aqflow .node small{display:block;color:#74858e;font-size:8px;margin-top:6px}.aqrecent{display:grid;gap:7px}.aqrecent .row{display:grid;grid-template-columns:95px 1fr auto;gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid #edf2f5;font-size:9px}.aqrecent .row:last-child{border-bottom:0}
 .aqgrid{display:grid;grid-template-columns:330px 1fr;gap:12px}.aqlist{max-height:640px;overflow:auto;padding-right:3px}.aqitem{padding:11px;border:1px solid #dce6eb;border-radius:9px;margin-bottom:7px;cursor:pointer;background:#fff}.aqitem:hover{border-color:#76bddb}.aqitem.on{border:2px solid #168ec3;background:#eef8fd}.aqitem .tag{display:inline-block;font-size:8px;padding:3px 6px;border-radius:999px;background:#eaf7fc;color:#0878bd;font-weight:900;margin-bottom:5px}.aqitem b{display:block;font-size:11px}.aqmeta{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.aqmeta>div{background:#f6f9fb;border:1px solid #e8eef2;border-radius:8px;padding:10px}.aqmeta .v{display:block;font-size:11px;font-weight:900;margin-top:4px}.aqout{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.aqout .out{border:1px solid #dfe8ed;border-radius:8px;padding:9px;background:#fbfdfe}.aqout .out b{font-size:10px}.aqout .out small{display:block;margin-top:4px;color:#7b8b93;font-size:8px}.aqrel{display:flex;gap:6px;flex-wrap:wrap}.aqrel button{border:1px solid #a9d6e9;background:#eef9fd;color:#12698f;border-radius:7px;padding:7px 9px;font-size:9px;cursor:pointer}.aqhist{width:100%;border-collapse:collapse}.aqhist th,.aqhist td{padding:9px;border-bottom:1px solid #e2eaee;text-align:left;font-size:9px}.aqhist th{background:#f5f8fa}.aqlink{display:inline-block;padding:8px 11px;border-radius:8px;background:#0d78a8;color:white;text-decoration:none;font-size:9px;font-weight:800}.aqlink.off{background:#e8edf0;color:#7d8b93;pointer-events:none}.aqactions{display:flex;gap:7px;flex-wrap:wrap}.aqstatus{display:inline-block;padding:4px 7px;border-radius:999px;font-size:8px;font-weight:900;background:#e5f7ef;color:#087c51}.aqsearch{width:100%;border:1px solid #d9e4e9;border-radius:8px;padding:9px 10px;margin-bottom:9px;font-size:10px}.aqempty{text-align:center;color:#7e8d95;padding:30px 10px;font-size:10px}
 @media(max-width:1100px){.aqmetrics{grid-template-columns:repeat(3,1fr)}.aqflow{grid-template-columns:repeat(2,1fr)}}@media(max-width:900px){.aqgrid,.aqdashgrid{grid-template-columns:1fr}.aqmeta{grid-template-columns:1fr 1fr}.aqmetrics{grid-template-columns:1fr 1fr}.aqout{grid-template-columns:1fr}}
 `;document.head.appendChild(x)}
 function ensure(){style();const main=document.querySelector('main')||document.querySelector('.main')||document.body;if(document.getElementById('aqmsView'))return;const v=document.createElement('section');v.id='aqmsView';v.className='view';v.innerHTML=`<div class="aqhero"><div><h2>AQMS 문서 / 프로세스 관리</h2><p>프로세스와 지침서, 관련 양식·산출물, 현재 Rev와 변경이력을 한 화면에서 추적합니다.<br>문서를 덮어쓰지 않고 개정 이력을 누적하여 AQMS 기록의 추적성을 유지합니다.</p></div><span class="aqhero-badge">AQMS DOCUMENT CONTROL</span></div><div class="aqtabs"><button data-aqt="대시보드" class="on">통합 현황</button><button data-aqt="프로세스">프로세스</button><button data-aqt="지침서">지침서</button><button data-aqt="산출물">양식 / 산출물</button><button data-aqt="이력">Rev / 변경이력</button></div><div id="aqmsBody"></div>`;const footer=main.querySelector('.footer');if(footer)main.insertBefore(v,footer);else main.appendChild(v);v.querySelectorAll('[data-aqt]').forEach(b=>b.onclick=()=>openTab(b.dataset.aqt))}
 function setHeader(){const t=document.getElementById('title'),sub=document.getElementById('sub');if(t)t.textContent='AQMS 통합 관리';if(sub)sub.textContent='프로세스 · 지침서 · 산출물 · Rev · 변경이력을 연결하여 관리합니다.'}
 function openView(){ensure();document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));const v=document.getElementById('aqmsView');v.classList.add('active');document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.v==='aqms'));setHeader();openTab(currentTab);window.scrollTo({top:0,left:0,behavior:'auto'})}
 function openTab(tab){currentTab=tab;const v=document.getElementById('aqmsView');if(!v)return;v.querySelectorAll('[data-aqt]').forEach(x=>x.classList.toggle('on',x.dataset.aqt===tab));render(tab)}
 function metrics(){const outs=[...new Set(docs.flatMap(d=>d.outputs||[]))], linked=docs.filter(d=>d.link).length, h=history();return {proc:docs.filter(d=>d.type==='프로세스').length,inst:docs.filter(d=>d.type==='지침서').length,outs:outs.length,linked,hist:h.length}}
 function render(tab='대시보드'){const body=document.getElementById('aqmsBody');if(!body)return;if(tab==='대시보드')return renderDash(body);if(tab==='산출물')return renderOutputs(body);if(tab==='이력')return renderHistory(body);return renderDocs(body,tab)}
 function renderDash(body){const m=metrics(),h=history(),processes=docs.filter(d=>d.type==='프로세스');body.innerHTML=`<div class="aqmetrics"><div class="aqmetric"><span>등록 프로세스</span><b>${m.proc}</b></div><div class="aqmetric"><span>등록 지침서</span><b>${m.inst}</b></div><div class="aqmetric"><span>연결 양식 / 산출물</span><b>${m.outs}</b></div><div class="aqmetric ${m.linked?'good':'warn'}"><span>원문 링크 등록</span><b>${m.linked}/${docs.length}</b></div><div class="aqmetric"><span>누적 Rev / 변경이력</span><b>${m.hist}</b></div></div><div class="aqdashgrid"><div><div class="aqsection"><div class="aqsection-title"><b>프로세스 체계</b><span class="small">카드를 누르면 문서 상세로 이동</span></div><div class="aqflow">${processes.map(d=>`<div class="node" onclick="window.aqmsOpen('${esc(d.id)}')"><span class="kind">${esc(d.type)}</span><b>${esc(d.title)}</b><small>${esc(d.owner)} · Rev ${esc(d.rev)}</small></div>`).join('')}</div></div><div class="aqsection"><div class="aqsection-title"><b>문서관리 원칙</b><span class="aqstatus">추적성 유지</span></div><div class="notice" style="margin:0"><b>현재본 관리</b> / 문서번호 · Rev · 시행일 · 주관부서를 함께 관리합니다.<br><br><b>개정 관리</b> / 변경 시 변경자 · 변경일시 · 변경사유 · 이전 Rev → 신규 Rev를 누적합니다.<br><br><b>산출물 관리</b> / 각 프로세스·지침서와 실제 양식 및 기록을 연결합니다.</div></div></div><div><div class="aqsection"><div class="aqsection-title"><b>최근 Rev / 변경 이력</b><button class="btn secondary" onclick="window.aqmsTab('이력')">전체보기</button></div><div class="aqrecent">${h.length?h.slice(0,6).map(x=>`<div class="row"><span>${esc(x.at)}</span><div><b>${esc(x.title)}</b><div class="small">${esc(x.from)} → ${esc(x.to)} · ${esc(x.reason)}</div></div><span>${esc(x.user)}</span></div>`).join(''):'<div class="aqempty">아직 등록된 개정이력이 없습니다.<br>문서의 Rev를 수정하면 이곳에 자동 누적됩니다.</div>'}</div></div><div class="aqsection"><div class="aqsection-title"><b>원문 연결 상태</b></div>${docs.slice(0,8).map(d=>`<div style="display:flex;justify-content:space-between;gap:8px;padding:7px 0;border-bottom:1px solid #edf2f5;font-size:9px"><span>${esc(d.title)}</span><span class="${d.link?'aqstatus':'status warn'}">${d.link?'연결됨':'링크 미등록'}</span></div>`).join('')}</div></div></div>`}
 function renderDocs(body,tab){const list=docs.filter(d=>d.type===tab);if(!list.some(d=>d.id===selected))selected=list[0]?.id||'';const d=docs.find(x=>x.id===selected)||list[0];body.innerHTML=`<div class="aqgrid"><div class="aqsection" style="margin:0"><input class="aqsearch" id="aqSearch" placeholder="문서명 / 문서번호 / 주관부서 검색"><div class="aqlist" id="aqList">${docList(list,d)}</div></div><div class="aqsection" style="margin:0" id="aqDetail">${d?detail(d):'<div class="aqempty">등록 문서가 없습니다.</div>'}</div></div>`;const search=document.getElementById('aqSearch');search.oninput=()=>{const q=search.value.toLowerCase();const f=list.filter(x=>[x.title,x.no,x.owner].some(v=>String(v).toLowerCase().includes(q)));document.getElementById('aqList').innerHTML=docList(f,d);bindList(tab)};bindList(tab)}
 function docList(list,d){return list.map(x=>`<div class="aqitem ${x.id===d?.id?'on':''}" data-aqid="${esc(x.id)}"><span class="tag">${esc(x.type)}</span><b>${esc(x.title)}</b><div class="small">${esc(x.no)} · Rev ${esc(x.rev)} · ${esc(x.owner)}</div></div>`).join('')||'<div class="aqempty">검색 결과가 없습니다.</div>'}
 function bindList(tab){document.querySelectorAll('#aqList [data-aqid]').forEach(x=>x.onclick=()=>{selected=x.dataset.aqid;renderDocs(document.getElementById('aqmsBody'),tab)})}
 function detail(d){const related=(d.related||[]).map(id=>docs.find(x=>x.id===id)).filter(Boolean);return `<div class="head"><div><span class="aqstatus">${esc(d.status||'현행')}</span><h2 style="margin-top:7px">${esc(d.title)}</h2><div class="small">${esc(d.type)} / ${esc(d.no)}</div></div><div class="aqactions"><button class="btn secondary" onclick="window.aqmsEdit('${esc(d.id)}')">문서정보 수정</button><button class="btn primary" onclick="window.aqmsRev('${esc(d.id)}')">Rev 개정</button></div></div><div class="aqmeta"><div><span class="small">현재 Rev</span><span class="v">${esc(d.rev)}</span></div><div><span class="small">시행일</span><span class="v">${esc(d.date)}</span></div><div><span class="small">주관부서</span><span class="v">${esc(d.owner)}</span></div><div><span class="small">문서번호</span><span class="v">${esc(d.no)}</span></div></div><div style="margin-top:16px"><div class="aqsection-title"><b>현재 승인 문서</b><span class="small">원문 PDF / Word / 사내 문서 링크</span></div>${d.link?`<a class="aqlink" href="${esc(d.link)}" target="_blank" rel="noopener">현재 Rev 문서 열기</a>`:'<span class="aqlink off">원문 링크 미등록</span>'}</div><div style="margin-top:18px"><div class="aqsection-title"><b>연결 프로세스 / 지침서</b><span class="small">상호 참조</span></div><div class="aqrel">${related.length?related.map(x=>`<button onclick="window.aqmsOpen('${esc(x.id)}')">${esc(x.type)} · ${esc(x.title)}</button>`).join(''):'<span class="small">연결 문서 없음</span>'}</div></div><div style="margin-top:18px"><div class="aqsection-title"><b>양식 / 산출물</b><span class="small">해당 업무 수행 시 생성·보존되는 기록</span></div><div class="aqout">${(d.outputs||[]).map(x=>`<div class="out"><b>${esc(x)}</b><small>관련 문서: ${esc(d.title)}</small></div>`).join('')||'<div class="aqempty">등록된 산출물이 없습니다.</div>'}</div></div><div style="margin-top:18px"><div class="aqsection-title"><b>이 문서의 최근 변경</b></div>${docHistory(d)}</div>`}
 function docHistory(d){const h=history().filter(x=>x.id===d.id).slice(0,5);return h.length?`<table class="aqhist"><thead><tr><th>일시</th><th>Rev</th><th>변경자</th><th>사유</th></tr></thead><tbody>${h.map(x=>`<tr><td>${esc(x.at)}</td><td>${esc(x.from)} → ${esc(x.to)}</td><td>${esc(x.user)}</td><td>${esc(x.reason)}</td></tr>`).join('')}</tbody></table>`:'<div class="small">등록된 변경이력이 없습니다.</div>'}
 function renderOutputs(body){const rows=[];docs.forEach(d=>(d.outputs||[]).forEach(o=>rows.push({name:o,doc:d})));body.innerHTML=`<div class="aqsection"><div class="aqsection-title"><div><b>양식 / 산출물 Master</b><div class="small">어떤 프로세스·지침서에서 어떤 기록이 생성되는지 역추적할 수 있습니다.</div></div><span class="aqstatus">${rows.length}개 연결</span></div><table class="aqhist"><thead><tr><th>양식 / 산출물</th><th>구분</th><th>관련 프로세스 / 지침서</th><th>문서번호</th><th>현재 Rev</th><th>주관</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.doc.type)}</td><td><button class="btn secondary" onclick="window.aqmsOpen('${esc(x.doc.id)}')">${esc(x.doc.title)}</button></td><td>${esc(x.doc.no)}</td><td>${esc(x.doc.rev)}</td><td>${esc(x.doc.owner)}</td></tr>`).join('')}</tbody></table></div>`}
 function renderHistory(body){const h=history();body.innerHTML=`<div class="aqsection"><div class="aqsection-title"><div><b>Rev / 변경관리 이력</b><div class="small">삭제하지 않고 모든 문서 개정 이력을 시간순으로 누적합니다.</div></div><span class="aqstatus">Audit Trail</span></div><table class="aqhist"><thead><tr><th>변경일시</th><th>문서</th><th>구분</th><th>Rev 변경</th><th>변경자</th><th>변경사유</th></tr></thead><tbody>${h.length?h.map(x=>`<tr><td>${esc(x.at)}</td><td><b>${esc(x.title)}</b><div class="small">${esc(x.no)}</div></td><td>${esc(x.action)}</td><td>${esc(x.from)} → ${esc(x.to)}</td><td>${esc(x.user)}</td><td>${esc(x.reason)}</td></tr>`).join(''):'<tr><td colspan="6" class="aqempty">등록된 변경이력이 없습니다.</td></tr>'}</tbody></table></div>`}
 window.aqmsTab=openTab;
 window.aqmsOpen=id=>{selected=id;const d=docs.find(x=>x.id===id);if(!d)return;openView();openTab(d.type)};
 window.aqmsEdit=id=>{const d=docs.find(x=>x.id===id);if(!d)return;const before=JSON.parse(JSON.stringify(d));const no=prompt('문서번호',d.no);if(no===null)return;const owner=prompt('주관부서',d.owner);if(owner===null)return;const link=prompt('현재 승인 문서 하이퍼링크 URL',d.link||'');if(link===null)return;const reason=prompt('변경 사유 (필수)','');if(!reason?.trim())return alert('변경 사유를 입력해야 합니다.');d.no=no.trim()||d.no;d.owner=owner.trim()||d.owner;d.link=link.trim();save(KEY,docs);audit('정보수정',d,before,d,reason.trim());render(currentTab)};
 window.aqmsRev=id=>{const d=docs.find(x=>x.id===id);if(!d)return;const before=JSON.parse(JSON.stringify(d));const rev=prompt('신규 Rev',d.rev==='미등록'?'Rev.0':d.rev);if(rev===null)return;const date=prompt('시행일 (YYYY-MM-DD)',d.date==='-'?new Date().toISOString().slice(0,10):d.date);if(date===null)return;const link=prompt('신규 Rev 문서 하이퍼링크 URL',d.link||'');if(link===null)return;const reason=prompt('개정 사유 (필수)','');if(!reason?.trim())return alert('개정 사유를 입력해야 합니다.');d.rev=rev.trim()||d.rev;d.date=date.trim()||d.date;d.link=link.trim();save(KEY,docs);audit('Rev 개정',d,before,d,reason.trim());render(currentTab)};
 function nav(){const nav=document.getElementById('nav');if(!nav)return;let b=nav.querySelector('[data-v="aqms"]');if(!b){const g=document.createElement('div');g.className='aqms-group';g.dataset.group='g-aqms';g.innerHTML='<div class="aqms-group-label">AQMS</div>';b=document.createElement('button');b.dataset.v='aqms';b.textContent='▤ 프로세스 / 지침서';g.appendChild(b);const admin=nav.querySelector('[data-group="g-admin"]');nav.insertBefore(g,admin||null)}b.onclick=e=>{e.preventDefault();e.stopPropagation();openView()}}
 ensure();nav();
})();