// WAVEPIA AQMS Document Center v2 - master reconstructed from supplied 2-page AQMS table
(function(){
 const KEY='wave_mes_aqms_docs_v2', HIST='wave_mes_aqms_history_v1';
 const D=(id,type,no,title,rev,enact,update,owner,outputs,related=[])=>({id,type,no,title,rev,enact,update,date:update&&update!=='-'?update:enact,owner,outputs,related,link:''});
 const docs=[
 D('P100','프로세스','WPQM-100','CMS 프로세스','03','17.07.01','25.07.21','품질',['품질 방침 및 목표','회의록'],['P401','P601','P701','P801','P802','P803','P804','P805','P806','P901','P902','P903']),
 D('P401','프로세스','WPQP-401','조직 상황 및 현황 관리 프로세스','02','17.07.01','26.08.04','경영',['이해관계자 요구사항표','통합목표 수립 계획서','내/외부 Issue 사항','당해년도 품질 방침 실적','SWOT 분석표','품질 방침 및 목표','조직도'],['P100']),
 D('P601','프로세스','WPQP-601','위험 및 기회 관리 프로세스','04','17.07.01','26.01.13','경영',['위험 및 기회 분석 평가표'],['P100']),
 D('P701','프로세스','WPQP-701','교육 훈련 프로세스','02','17.07.01','23.03.10','경영',['년간 교육 훈련 계획서','교육 보고서 (개인 교육)','교육 보고서 (단체 교육)','OJT 계획서','OJT 교육일지','OJT 지도 평가서'],['I710']),
 D('P801','프로세스','WPQP-801','영업 관리 프로세스','04','17.07.01','25.09.02','영업',['견적서','계약검토서','계약검토 회의록','납품(수주)관리대장','작업요청서','월간 보고서','고객사 리스트 관리대장'],['P901']),
 D('P802','프로세스','WPQP-802','설계 및 개발 관리 프로세스','03','17.07.01','26.01.15','연구소',['개발 계획서','요구사항 추적표','설계 보고서','개발 완료 보고서','BOM','시험 계획서','시험 성적서','개발 Issue 관련 대장'],['I802','I818']),
 D('P803','프로세스','WPQP-803','구매 및 협력사 관리 프로세스','05','17.07.01','26.07.07','구매',['품목 구매 협의서','발주서','협력업체 등록카드','협력업체 평가표','협력업체 승인 관리 대장','협력사 리스트 관리 대장','협력업체 품질 보증 협약서','인수인계증','발주 리스트','자재 불출 요청서','협력사 평가 계획서','거래 기본 계약서','거래명세서'],['I807','I808']),
 D('P804','프로세스','WPQP-804','부적합 및 시정조치 관리 프로세스','04','17.07.01','26.08.05','품질',['부적합품 보고서','부적합품 관리 대장','부적합품 식별표','부적합품 폐기 대장','부적합품 기술검토서','특채 신청서','특채 관리 대장','시정 및 예방조치 요구서','시정 및 예방조치 관리대장','폐기 신청서'],['I807','I821']),
 D('P805','프로세스','WPQP-805','공정관리 프로세스','04','23.02.16','26.08.07','생산',['생산계획서','제조공정도','작업지도서','작업절차서','부적합품 보고서'],['I702','I703','I704','I705','I706','I709','I710','I711','I806','I807','I810','I812','I813','I819']),
 D('P806','프로세스','WPQP-806','신뢰성 프로세스','00','25.04.11','-','품질',['설비 점검 기록부','초도품 평가표','Process & Design FMEA'],['I822']),
 D('P901','프로세스','WPQP-901','고객 만족 프로세스','03','17.07.01','25.09.02','영업',['고객 불만 처리 대장','고객 만족도 평가서','고객 불만 처리 결과서','고객 만족도 평가 대장'],['I821']),
 D('P902','프로세스','WPQP-902','내부 심사 프로세스','04','17.07.01','26.07.07','품질',['내부심사 계획서','내부심사 체크표','내부심사 결과 보고서','시정 및 예방조치 요구서'],[]),
 D('P903','프로세스','WPQP-903','경영검토 프로세스','04','17.07.01','25.02.26','경영',['경영검토 회의록','경영검토 보고서','KPI 자료 계획 실적표','KPI 관련 개선 대책서'],['I901']),

 D('I701','지침서','WPQI-701','지식 관리 지침서','01','17.07.01','22.07.01','경영',['지식 관리 대장'],[]),
 D('I702','지침서','WPQI-702','설비 관리 지침서','02','17.07.01','24.04.10','생산',['설비 관리 대장','설비 이력 카드','설비 일상 점검표','치공구 관리 대장','공구 주기 점검표','장비 이상 발생 보고서','치공구 이력 카드','설비 점검 기록부','설비 보전 계획서','Spare Part 관리대장','장비 운용 절차서'],['P805']),
 D('I703','지침서','WPQI-703','업무 환경 관리 지침서','01','17.07.01','22.07.01','생산',['청정도 체크시트','온/습도 체크시트','소화기 체크시트','미소립자 체크시트','포토 공정 체크시트'],['P805']),
 D('I704','지침서','WPQI-704','계측기 관리 지침서','03','17.07.01','24.03.27','연구소',['계측기 관리 대장','계측기 이력 카드','계측기 검교정표','계측기 수리 이력 관리대장','장비 수리 의뢰 품의서','장비 입고 확인서','계측기 검교정 합부 판정 기준서'],['P805']),
 D('I705','지침서','WPQI-705','유해물질 관리 지침서','01','17.07.01','22.07.01','생산',['MSDS 관리 대장','유해물질 응급 조치 기준서'],['P805','I820']),
 D('I706','지침서','WPQI-706','FOD 관리 지침서','02','17.07.01','25.09.10','생산',['FOD 예방 점검표','FOD 위험성 평가서','FOD 사고 보고서','FOD 성과 평가서','FO 발생 인자 발견 보고서','FOD 이행 상태 평가표'],['P805']),
 D('I707','지침서','WPQI-707','문서 및 기록 관리 지침서','02','17.07.01','25.09.09','품질',['표준문서 서식','표준문서 및 양식 관리대장','시스템에서 수신된 대장','시스템에서 수신된 대장','문서관리 대장','백업관리 대장'],[]),
 D('I708','지침서','WPQI-708','비상계획 지침서','01','17.07.01','22.07.01','경영',['비상 훈련 계획서','비상 훈련 보고서','비상 사태 체크도','비상 사태 시나리오'],[]),
 D('I709','지침서','WPQI-709','ESD & EOS 관리 지침서','03','17.07.01','25.12.15','생산',['EOS & ESD 점검 계획','EOS & ESD 점검 체크시트','ESD Try 표면저항 측정 관리대장'],['P805']),
 D('I710','지침서','WPQI-710','자격 및 인증 관리 지침서','05','17.07.01','25.09.10','품질',['자격자 이력서','자격 인증 관리 대장','적합성 평가표','인정 및 서명 관리 대장'],['P701','P805']),
 D('I711','지침서','WPQI-711','물류품 취급 관리 지침서','02','17.07.01','25.08.25','생산',['물류품 취급 평가 기준 Sheet','물류품 Audit Check Sheet','물류품 관리 대장','물류품 수리 내역 관리 대장','물류품 이상 발생 보고서','Particle Check Sheet'],['P805']),
 D('I802','지침서','WPQI-802','형상 관리 지침서','01','17.07.01','22.07.01','연구소',['형상 변경 요청서','형상 변경 식별서','형상 변경 관리 대장','기술 검토서','기술 변경 제안서'],['P802']),
 D('I803','지침서','WPQI-803','제품 안전 관리 지침서','01','17.07.01','22.07.01','생산',['제품 안전 관리 점검표'],[]),
 D('I804','지침서','WPQI-804','위변조품 관리 지침서','03','17.07.01','25.09.11','품질',['수입검사 성적서'],['P803','I807']),
 D('I805','지침서','WPQI-805','양산 이관 지침서','01','23.02.16','24.03.27','연구소',['양산이관 완료 보고서'],['P802','P805']),
 D('I806','지침서','WPQI-806','자재 및 제품관리 지침서','02','17.07.01','26.08.05','생산',['재고 현품 List'],['P803','P805']),
 D('I807','지침서','WPQI-807','검사 업무 지침서','03','17.07.01','25.09.11','품질',['수입검사 성적서','출하검사 의뢰서','수입검사 기준서','수입검사 / 공정검사 관련 대장','수입검사 대장','출하검사 성적서','출하검사 기준서','출하검사 기준서 관리 대장','출하검사 개선서','출하검사 기준서 관리 대장','출하검사 현황','자주검사 성적서','제품보증서 관리대장','3D스캐너검사 관리대장','입고검사 표준서'],['P803','P804','P805','I804']),
 D('I808','지침서','WPQI-808','특수공정 관리 지침서','02','17.07.01','25.09.11','품질',['특수공정 승인 요청서'],['P803']),
 D('I809','지침서','WPQI-809','초도품 관리 지침서','03','17.07.01','24.03.27','연구소',['초도품 검사 성적서','초도품 평가표'],['P806']),
 D('I810','지침서','WPQI-810','식별 및 추적성 관리 지침서','02','17.07.01','25.08.20','제조',['제품 일련번호 체계','웨이퍼 일련번호 코드 체계','제품 일련번호 관리 대장','제조공정 확인서'],['P805']),
 D('I811','지침서','WPQI-811','외부 자산 관리 지침서','03','17.07.01','25.09.02','영업',['고객 인수인계 관리 대장','협력사 인수인계 관리 대장'],[]),
 D('I812','지침서','WPQI-812','시효성 관리 지침서','04','17.07.01','26.03.20','제조',['시효성 자재 관리 대장','시효성 자재 식별표','시효성 자재 LIST'],['P805']),
 D('I813','지침서','WPQI-813','변경점 관리 지침서','01','17.07.01','22.07.01','생산',['변경점 신고서','변경점 관리 대장'],['P805']),
 D('I814','지침서','WPQI-814','도면 관리 지침서','04','17.07.01','24.03.27','연구소',['도면 관리 대장'],['P802']),
 D('I818','지침서','WPQI-818','소프트웨어 관리 지침서','00','25.04.29','-','연구소',['소프트웨어 관리 대장'],['P802']),
 D('I819','지침서','WPQI-819','포장관리 지침서','00','25.09.01','-','제조',['포장 표준작업 절차서 (SOP)','포장 Check List','포장검사기준서','포장 검사 기준서'],['P805']),
 D('I820','지침서','WPQP-820','환경유해물질 관리 지침서','00','25.09.04','-','구매',['환경유해물질 관리대장','REACH&SVHC 관리대장','유해물질 저항성 평가서'],['I705']),
 D('I821','지침서','WPQI-821','고객불만 지침서','00','25.04.11','-','품질',['RMA request form','불량분석보고서 (FAR)','불량분석보고서 (8D Report)'],['P804','P901']),
 D('I822','지침서','WPQI-822','신뢰성 지침서','00','25.04.29','-','품질',['신뢰성시험의뢰서','신뢰성시험결과보고서','Reliability test sheet','Qualification Report','General test report'],['P806']),
 D('I901','지침서','WPQI-901','데이터 분석 지침서','02','17.07.01','25.09.10','품질',['분기 품질결과 보고서'],['P903'])
 ];
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch(e){return d}};
 let db=load(KEY,null);if(!db){db=docs;save(KEY,db)}
 let selected=db[0]?.id||'';
 const hist=()=>load(HIST,[]);
 function actor(){try{return JSON.parse(sessionStorage.getItem('wave_mes_demo_login_v2')||'null')?.name||'DEMO 사용자'}catch(e){return'DEMO 사용자'}}
 function log(d,before,reason){const h=hist();h.unshift({at:new Date().toLocaleString('ko-KR'),no:d.no,title:d.title,from:before.rev,to:d.rev,user:actor(),reason});save(HIST,h);try{window.waveMesAudit?.('AQMS REV',d.no,d.no,before,d,reason)}catch(e){}}
 function style(){if(document.getElementById('aqmsV2Style'))return;const s=document.createElement('style');s.id='aqmsV2Style';s.textContent=`#aqmsView{display:none}.aq-hero{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:12px}.aq-kpi{padding:14px;border:1px solid #d7e5ed;border-radius:12px;background:#fff}.aq-kpi b{display:block;font-size:22px;margin-top:5px}.aq-tabs{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:12px}.aq-tabs button{padding:8px 12px;border:1px solid #d5e2e9;background:#fff;border-radius:8px;font-weight:800;cursor:pointer}.aq-tabs button.on{background:#0a7faf;color:#fff}.aq-grid{display:grid;grid-template-columns:370px 1fr;gap:12px}.aq-search{width:100%;padding:9px 10px;border:1px solid #d6e3ea;border-radius:8px;margin-bottom:8px}.aq-list{max-height:690px;overflow:auto}.aq-row{padding:10px;border:1px solid #dbe6ec;border-radius:9px;margin-bottom:6px;background:#fff;cursor:pointer}.aq-row.on{border:2px solid #1897c9;background:#edf9fe}.aq-type{font-size:9px;font-weight:900;color:#1384b1}.aq-meta{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.aq-meta>div{padding:10px;border-radius:9px;background:#f5f9fb}.aq-box{margin-top:13px;padding:12px;border:1px solid #dce7ec;border-radius:10px;background:#fff}.aq-chips{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.aq-chips span,.aq-chips button{padding:6px 9px;border:1px solid #cfe0e9;border-radius:999px;background:#f8fbfc;font-size:10px}.aq-chips button{cursor:pointer;color:#0876a3}.aq-hist{width:100%;border-collapse:collapse}.aq-hist td,.aq-hist th{padding:8px;border-bottom:1px solid #e3eaee;font-size:10px;text-align:left}.aq-link{display:inline-block;padding:8px 11px;border-radius:8px;background:#0a7faf;color:#fff;text-decoration:none;font-weight:800}.aq-link.off{background:#e9eef1;color:#7e8b93;pointer-events:none}@media(max-width:950px){.aq-grid{grid-template-columns:1fr}.aq-hero{grid-template-columns:1fr 1fr}.aq-meta{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
 function ensure(){style();let v=document.getElementById('aqmsView');if(!v){v=document.createElement('section');v.id='aqmsView';v.className='view';(document.querySelector('main')||document.body).appendChild(v)}v.innerHTML=`<div class="head"><div><h2>AQMS 통합 관리</h2><div class="small">회사 AQMS 규격표 기준 프로세스 / 지침서 / 산출물 / Rev·변경이력</div></div><span class="status good">AQMS MASTER</span></div><div class="aq-hero"><div class="aq-kpi"><span class="small">프로세스</span><b>${db.filter(x=>x.type==='프로세스').length}</b></div><div class="aq-kpi"><span class="small">지침서</span><b>${db.filter(x=>x.type==='지침서').length}</b></div><div class="aq-kpi"><span class="small">연결 산출물</span><b>${new Set(db.flatMap(x=>x.outputs)).size}</b></div><div class="aq-kpi"><span class="small">Rev 변경이력</span><b>${hist().length}</b></div></div><div class="card"><div class="aq-tabs"><button data-tab="전체" class="on">전체</button><button data-tab="프로세스">프로세스</button><button data-tab="지침서">지침서</button><button data-tab="산출물">양식 / 산출물</button><button data-tab="이력">Rev / 변경이력</button></div><div id="aqV2Body"></div></div>`;v.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{v.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('on'));b.classList.add('on');render(b.dataset.tab)})}
 function detail(d){const rel=(d.related||[]).map(id=>db.find(x=>x.id===id)).filter(Boolean);return `<div class="head"><div><h2>${esc(d.title)}</h2><div class="small"><b>${esc(d.no)}</b> / ${esc(d.type)}</div></div><button class="btn secondary" onclick="aqmsEditV2('${d.id}')">Rev / 문서정보 수정</button></div><div class="aq-meta"><div><span class="small">Rev</span><b>${esc(d.rev)}</b></div><div><span class="small">제정</span><b>${esc(d.enact)}</b></div><div><span class="small">최근 개정</span><b>${esc(d.update)}</b></div><div><span class="small">주관</span><b>${esc(d.owner)}</b></div><div><span class="small">문서번호</span><b>${esc(d.no)}</b></div></div><div class="aq-box"><b>현재 승인 문서</b><div style="margin-top:8px">${d.link?`<a class="aq-link" href="${esc(d.link)}" target="_blank">문서 열기</a>`:'<span class="aq-link off">하이퍼링크 미등록</span>'}</div></div><div class="aq-box"><b>관련 프로세스 / 지침서</b><div class="aq-chips">${rel.length?rel.map(x=>`<button onclick="aqmsOpenV2('${x.id}')">${esc(x.no)} · ${esc(x.title)}</button>`).join(''):'<span>연결 문서 없음</span>'}</div></div><div class="aq-box"><b>양식 / 산출물 (${d.outputs.length})</b><div class="aq-chips">${d.outputs.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div><div class="aq-box"><b>이 문서의 변경이력</b><table class="aq-hist"><tbody>${hist().filter(x=>x.no===d.no).slice(0,8).map(x=>`<tr><td>${esc(x.at)}</td><td>Rev ${esc(x.from)} → ${esc(x.to)}</td><td>${esc(x.user)}</td><td>${esc(x.reason)}</td></tr>`).join('')||'<tr><td>등록된 변경이력이 없습니다.</td></tr>'}</tbody></table></div>`}
 function render(tab='전체'){const body=document.getElementById('aqV2Body');if(!body)return;if(tab==='산출물'){const map={};db.forEach(d=>d.outputs.forEach(o=>(map[o]??=[]).push(d)));body.innerHTML=`<table class="aq-hist"><thead><tr><th>양식 / 산출물</th><th>연결 프로세스 / 지침서</th></tr></thead><tbody>${Object.entries(map).sort().map(([o,a])=>`<tr><td><b>${esc(o)}</b></td><td>${a.map(x=>`${esc(x.no)} ${esc(x.title)}`).join('<br>')}</td></tr>`).join('')}</tbody></table>`;return}if(tab==='이력'){body.innerHTML=`<table class="aq-hist"><thead><tr><th>변경일시</th><th>문서</th><th>Rev</th><th>변경자</th><th>사유</th></tr></thead><tbody>${hist().map(x=>`<tr><td>${esc(x.at)}</td><td>${esc(x.no)} / ${esc(x.title)}</td><td>${esc(x.from)} → ${esc(x.to)}</td><td>${esc(x.user)}</td><td>${esc(x.reason)}</td></tr>`).join('')||'<tr><td colspan="5">변경이력이 없습니다.</td></tr>'}</tbody></table>`;return}let list=tab==='전체'?db:db.filter(x=>x.type===tab);if(!list.find(x=>x.id===selected))selected=list[0]?.id||'';const d=db.find(x=>x.id===selected)||list[0];body.innerHTML=`<div class="aq-grid"><div><input id="aqSearchV2" class="aq-search" placeholder="문서번호 / 명칭 / 주관 검색"><div class="aq-list" id="aqListV2">${rows(list,d)}</div></div><div id="aqDetailV2">${d?detail(d):''}</div></div>`;const inp=document.getElementById('aqSearchV2');inp.oninput=()=>{const q=inp.value.toLowerCase();document.getElementById('aqListV2').innerHTML=rows(list.filter(x=>[x.no,x.title,x.owner].some(v=>String(v).toLowerCase().includes(q))),db.find(x=>x.id===selected));bindRows(tab)};bindRows(tab)}
 function rows(list,d){return list.map(x=>`<div class="aq-row ${x.id===d?.id?'on':''}" data-aqid="${x.id}"><span class="aq-type">${esc(x.type)}</span><br><b>${esc(x.title)}</b><div class="small">${esc(x.no)} / Rev ${esc(x.rev)} / ${esc(x.owner)}</div></div>`).join('')}
 function bindRows(tab){document.querySelectorAll('#aqListV2 [data-aqid]').forEach(r=>r.onclick=()=>{selected=r.dataset.aqid;render(tab)})}
 window.aqmsOpenV2=id=>{selected=id;render(db.find(x=>x.id===id)?.type||'전체')};
 window.aqmsEditV2=id=>{const d=db.find(x=>x.id===id);if(!d)return;const before=JSON.parse(JSON.stringify(d));const rev=prompt('신규 Rev',d.rev);if(rev===null)return;const update=prompt('개정일 (YY.MM.DD)',d.update);if(update===null)return;const link=prompt('현재 승인 문서 URL / 사내 링크',d.link||'');if(link===null)return;const reason=prompt('변경 사유 (필수)','');if(!reason?.trim())return alert('변경 사유를 입력해야 합니다.');d.rev=rev.trim()||d.rev;d.update=update.trim()||d.update;d.date=d.update;d.link=link.trim();save(KEY,db);log(d,before,reason.trim());ensure();render(document.querySelector('#aqmsView [data-tab].on')?.dataset.tab||'전체')};
 window.waveAqmsV2={show(){ensure();document.querySelectorAll('.view').forEach(x=>{x.classList.remove('active');x.style.display='none'});const v=document.getElementById('aqmsView');v.style.display='block';v.classList.add('active');const t=document.getElementById('title'),sub=document.getElementById('sub');if(t)t.textContent='AQMS 통합 관리';if(sub)sub.textContent='회사 AQMS 규격표 기준 프로세스 · 지침서 · 산출물 · Rev / 변경이력';render('전체');window.scrollTo(0,0)}};
 setTimeout(()=>{ensure();const b=document.querySelector('#nav [data-v="aqms"]');if(b)b.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===b));window.waveAqmsV2.show()}},180);
})();