// WAVEPIA AQMS Document Center - additive layer, no changes to MES runtime/storage
(function(){
 const KEY='wave_mes_aqms_docs_v1', HIST='wave_mes_aqms_history_v1';
 const seed=[
  {id:'P-PROD',type:'프로세스',no:'AQMS-PROD',title:'생산 및 서비스 제공',rev:'현행',date:'-',owner:'생산',link:'',outputs:['작업요청서','디지털 LTC','작업실적','포장 기록'],related:['I-TRACE','I-INSP','I-NC']},
  {id:'P-PUR',type:'프로세스',no:'AQMS-PUR',title:'구매 및 외부공급자 관리',rev:'현행',date:'-',owner:'구매 / 자재',link:'',outputs:['발주 기록','입고 기록','수입검사 기록','공급자 평가'],related:['I-INSP']},
  {id:'P-DEV',type:'프로세스',no:'AQMS-DEV',title:'설계 및 개발 관리',rev:'현행',date:'-',owner:'개발',link:'',outputs:['개발계획','설계검토 기록','검증 / 유효성 확인 기록','변경 기록'],related:['I-CONFIG']},
  {id:'P-NC',type:'프로세스',no:'AQMS-NC',title:'부적합 및 시정조치 관리',rev:'현행',date:'-',owner:'품질',link:'',outputs:['NCR','CAR','8D Report','시정 / 예방조치 기록'],related:['I-NC']},
  {id:'I-TRACE',type:'지침서',no:'AQMS-I-TRACE',title:'식별 및 추적성 관리',rev:'현행',date:'-',owner:'생산 / 품질',link:'',outputs:['LOT / LTC 식별 기록','PO / 기안번호 추적 기록','공정 이력'],related:['P-PROD']},
  {id:'I-INSP',type:'지침서',no:'AQMS-I-INSP',title:'검사 업무',rev:'현행',date:'-',owner:'품질',link:'',outputs:['수입검사 기록','공정검사 기록','출하검사 기록','검사 성적서'],related:['P-PROD','P-PUR']},
  {id:'I-NC',type:'지침서',no:'AQMS-I-NC',title:'부적합 관리',rev:'현행',date:'-',owner:'품질',link:'',outputs:['부적합 보고서','HOLD / CLEAR 이력','처리 판정 기록'],related:['P-NC','P-PROD']},
  {id:'I-CONFIG',type:'지침서',no:'AQMS-I-CONFIG',title:'형상 및 변경 관리',rev:'현행',date:'-',owner:'개발 / 품질',link:'',outputs:['BOM Rev','도면 Rev','변경 승인 기록','형상 기준선'],related:['P-DEV']}
 ];
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch(e){return d}};
 const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 let docs=load(KEY,null); if(!docs){docs=seed;save(KEY,docs)}
 let selected=docs[0]?.id||'';
 function hist(){return load(HIST,[])}
 function audit(action,d,before,after,reason){const row={at:new Date().toLocaleString('ko-KR'),action,id:d.id,no:d.no,title:d.title,from:before?.rev||'-',to:after?.rev||d.rev,reason:reason||'-',user:(JSON.parse(sessionStorage.getItem('wave_mes_demo_login_v2')||'null')||{}).name||'DEMO 사용자'};const h=hist();h.unshift(row);save(HIST,h);try{window.waveMesAudit?.('AQMS '+action,d.no,d.no,before,after,reason)}catch(e){}}
 function style(){if(document.getElementById('aqmsDocStyle'))return;const x=document.createElement('style');x.id='aqmsDocStyle';x.textContent=`
 #aqmsView .aqtabs{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:12px}#aqmsView .aqtabs button{border:1px solid #d6e3ea;background:#fff;border-radius:8px;padding:8px 12px;font-weight:800;cursor:pointer}#aqmsView .aqtabs button.on{background:#0d78a8;color:#fff;border-color:#0d78a8}.aqgrid{display:grid;grid-template-columns:330px 1fr;gap:12px}.aqlist{max-height:650px;overflow:auto}.aqitem{padding:11px;border:1px solid #dce6eb;border-radius:9px;margin-bottom:7px;cursor:pointer;background:#fff}.aqitem.on{border:2px solid #168ec3;background:#eef8fd}.aqmeta{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.aqmeta>div{background:#f6f9fb;border-radius:8px;padding:9px}.aqout{display:flex;gap:6px;flex-wrap:wrap}.aqout span{border:1px solid #d9e4ea;border-radius:999px;padding:6px 9px;background:#fff}.aqrel{display:flex;gap:6px;flex-wrap:wrap}.aqrel button{border:1px solid #a9d6e9;background:#eef9fd;color:#12698f;border-radius:7px;padding:6px 9px;cursor:pointer}.aqhist{width:100%;border-collapse:collapse}.aqhist th,.aqhist td{padding:7px;border-bottom:1px solid #e2eaee;text-align:left;font-size:11px}.aqlink{display:inline-block;padding:8px 11px;border-radius:8px;background:#0d78a8;color:white;text-decoration:none;font-weight:800}.aqlink.off{background:#e8edf0;color:#7d8b93;pointer-events:none}@media(max-width:900px){.aqgrid{grid-template-columns:1fr}.aqmeta{grid-template-columns:1fr 1fr}}
 `;document.head.appendChild(x)}
 function ensure(){style();const main=document.querySelector('main')||document.querySelector('.main')||document.body;if(document.getElementById('aqmsView'))return;const v=document.createElement('section');v.id='aqmsView';v.className='view';v.style.display='none';v.innerHTML=`<div class="head"><div><h2>AQMS</h2><div class="small">프로세스 / 지침서 / 양식·산출물 / Rev·변경이력 통합 관리</div></div><span class="status good">Document Control</span></div><div class="card"><div class="aqtabs"><button data-aqt="전체" class="on">전체</button><button data-aqt="프로세스">프로세스</button><button data-aqt="지침서">지침서</button><button data-aqt="산출물">양식 / 산출물</button><button data-aqt="이력">개정이력</button></div><div id="aqmsBody"></div></div>`;main.appendChild(v);v.querySelectorAll('[data-aqt]').forEach(b=>b.onclick=()=>{v.querySelectorAll('[data-aqt]').forEach(x=>x.classList.remove('on'));b.classList.add('on');render(b.dataset.aqt)})}
 function render(tab='전체'){const body=document.getElementById('aqmsBody');if(!body)return;if(tab==='산출물'){const all=[...new Set(docs.flatMap(d=>d.outputs||[]))];body.innerHTML=`<div class="head"><div><b>등록 양식 / 산출물</b><div class="small">각 문서에 연결된 기록 및 양식 목록</div></div></div><div class="aqout">${all.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`;return}if(tab==='이력'){const h=hist();body.innerHTML=`<table class="aqhist"><thead><tr><th>변경일시</th><th>문서</th><th>Rev</th><th>변경자</th><th>사유</th></tr></thead><tbody>${h.length?h.map(x=>`<tr><td>${esc(x.at)}</td><td>${esc(x.no)} / ${esc(x.title)}</td><td>${esc(x.from)} → ${esc(x.to)}</td><td>${esc(x.user)}</td><td>${esc(x.reason)}</td></tr>`).join(''):'<tr><td colspan="5">등록된 개정이력이 없습니다.</td></tr>'}</tbody></table>`;return}const list=tab==='전체'?docs:docs.filter(d=>d.type===tab);if(!list.some(d=>d.id===selected))selected=list[0]?.id||'';const d=docs.find(x=>x.id===selected)||list[0];body.innerHTML=`<div class="aqgrid"><div class="aqlist">${list.map(x=>`<div class="aqitem ${x.id===d?.id?'on':''}" data-aqid="${esc(x.id)}"><b>${esc(x.title)}</b><div class="small">${esc(x.type)} / ${esc(x.no)} / Rev ${esc(x.rev)}</div></div>`).join('')}</div><div>${d?detail(d):'<div class="small">등록 문서가 없습니다.</div>'}</div></div>`;body.querySelectorAll('[data-aqid]').forEach(x=>x.onclick=()=>{selected=x.dataset.aqid;render(tab)})}
 function detail(d){const related=(d.related||[]).map(id=>docs.find(x=>x.id===id)).filter(Boolean);return `<div class="head"><div><h2>${esc(d.title)}</h2><div class="small">${esc(d.type)} / ${esc(d.no)}</div></div><button class="btn" onclick="window.aqmsRev('${esc(d.id)}')">Rev / 문서정보 수정</button></div><div class="aqmeta"><div><div class="small">현재 Rev</div><b>${esc(d.rev)}</b></div><div><div class="small">시행일</div><b>${esc(d.date)}</b></div><div><div class="small">주관</div><b>${esc(d.owner)}</b></div><div><div class="small">문서번호</div><b>${esc(d.no)}</b></div></div><div style="margin-top:14px"><b>현재 문서</b><div style="margin-top:7px">${d.link?`<a class="aqlink" href="${esc(d.link)}" target="_blank" rel="noopener">프로세스 / 지침서 열기</a>`:'<span class="aqlink off">문서 링크 미등록</span>'}</div></div><div style="margin-top:16px"><b>관련 프로세스 / 지침서</b><div class="aqrel" style="margin-top:7px">${related.length?related.map(x=>`<button onclick="window.aqmsOpen('${esc(x.id)}')">${esc(x.title)}</button>`).join(''):'<span class="small">연결 문서 없음</span>'}</div></div><div style="margin-top:16px"><b>양식 / 산출물</b><div class="aqout" style="margin-top:7px">${(d.outputs||[]).map(x=>`<span>${esc(x)}</span>`).join('')||'<span>미등록</span>'}</div></div>`}
 window.aqmsOpen=id=>{selected=id;render(docs.find(x=>x.id===id)?.type||'전체')};
 window.aqmsRev=id=>{const d=docs.find(x=>x.id===id);if(!d)return;const before=JSON.parse(JSON.stringify(d));const rev=prompt('신규 Rev',d.rev);if(rev===null)return;const date=prompt('시행일 (YYYY-MM-DD)',d.date);if(date===null)return;const link=prompt('현재 문서 하이퍼링크 URL',d.link||'');if(link===null)return;const reason=prompt('변경 사유 (필수)','');if(!reason?.trim())return alert('변경 사유를 입력해야 합니다.');d.rev=rev.trim()||d.rev;d.date=date.trim()||d.date;d.link=link.trim();save(KEY,docs);audit('개정',d,before,d,reason.trim());render(document.querySelector('#aqmsView [data-aqt].on')?.dataset.aqt||'전체')};
 function nav(){const nav=document.getElementById('nav');if(!nav||nav.querySelector('[data-v="aqms"]'))return;const g=document.createElement('div');g.className='aqms-group';g.dataset.group='g-aqms';g.innerHTML='<div class="aqms-group-label">AQMS</div>';const b=document.createElement('button');b.dataset.v='aqms';b.textContent='프로세스 / 지침서';b.onclick=()=>{document.querySelectorAll('.view').forEach(x=>x.style.display='none');document.getElementById('aqmsView').style.display='block';document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===b));render('전체');window.scrollTo(0,0)};g.appendChild(b);const admin=nav.querySelector('[data-group="g-admin"]');nav.insertBefore(g,admin||null)}
 ensure();nav();
})();